In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4,5]
arr = np.array(l)
arr 


array([1, 2, 3, 4, 5])

In [ ]:
arr=np.arange(101)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
arr=np.arange(5,10)
arr

array([5, 6, 7, 8, 9])

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr.size


6

In [ ]:
arr=np.arange(10)
arr.ndim

1

In [ ]:
arr=np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [ ]:
arr=np.array([[1,2,3,4,5,6,7]])
arr.shape

(1, 7)

In [ ]:
a=np.arange(1,6)
b=np.arange(6,11)
print(a+b)
print(b-a)
print(a*b)
print(b//a)
print(b/a)
print(b%a)


[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[6 3 2 2 2]
[6.         3.5        2.66666667 2.25       2.        ]
[0 1 2 1 0]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.cross(a,b)


array([-3,  6, -3])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.dot(a,b)

np.int64(32)

In [ ]:
arr=np.array([1,2,3,4])
np.cumprod(arr)


array([ 1,  2,  6, 24])

In [ ]:
n=123
a=n
rev=0
while a>0:
    t=a%10
    rev=rev*10+t
    a=a//10
print(rev)


321


In [ ]:
n = int(input("enter a number"))
sq=n**2
r=0
while sq>0:
    t=sq%10
    r+=t
    sq=sq//10
if r==n:
     print("neon number")
else:
    print("not a neon number")


not a neon number


In [2]:
n=int(input("enter a number"))
a=n//10%10
b=n//10%10
c=n//10%10
arm=a**3+b**3+c**3
if arm==n:
    print("arm number")
else:
      print("not arm number")

not arm number


In [5]:
num=(int(input("enter a number:")))
fact=1
for i in range(num ,0,-1):
    fact*=i
print("factorial of",num,"is",fact)


factorial of 2 is 2
